site_name: MengQiu Twenty-nine
site_url: https://weizhiwang221.github.io/cloud-native-journey/
site_description: 一名云计算运维工程师的云原生学习与实践之旅。

theme:
  #name: mkdocs
  name: windmill
  # 切换夜间模式
  color_mode: auto
  user_color_mode_toggle: true
  # 导航栏深度
  navigation_depth: 3
  locale: zh_CN
  # name: material
  # custom_dir: docs/overrides # (可选) 用于深度自定义，覆盖主题模板

# 插件
plugins:
  - search
  - awesome-pages

# 版权信息
copyright: |
  Copyright &copy; 2025 Weizhi Wang | 
  <a href="https://github.com/weizhiwang221/cloud-native-journey" target="_blank" rel="noopener">View on GitHub</a>

# 自定义CSS - 这是实现“Halo风格”的关键
extra_css:
  - stylesheets/extra.css